--10 PERGUNTAS
	--1)QUANTOS CACHORROS ESTÃO CADASTRADOS?
	--2)QUAIS ESPÉCIES DIFERENTES TEM?
	--3)ORGANIZE OS FUNCIONÁRIOS NA ORDEM ALFABÉTICA.
	--4)QUANTOS E QUAIS PRODUTOS ENTRE R$20 E R$70 TEM DISPONIVEIS?
	--5)QUANTAS VENDAS FORAM FEITAS NO TOTAL?
	--6)CONTE QUANTOS VETERINARIOS TEM.
	--7)AGORA CONTE QUANTOS ATENDENTES TEM.
	--8)QUAIS PRODUTOS COM VALOR INFERIOR A R$30 TEMOS(EXIBIR NOME E VALOR)?
	--9)QUAIS PORTES ESTÃO PRESENTES?
	--10)QUAL A MÉDIA SALARIAL BASEADA NAS FUNÇÕES?

--RESPOSTAS
USE PROJETO;
--1)
SELECT COUNT(P.ESPECIE) QTD_CACHORROS
FROM DBO.PET AS p
WHERE P.ESPECIE = 'CACHORRO';
--2)
SELECT
	DISTINCT P.ESPECIE 
FROM DBO.PET AS p;
--3)
SELECT *
FROM DBO.FUNCIONARIO AS F
ORDER BY F.NOME ASC;
--4)
SELECT P.NOME, P.VALOR
FROM DBO.PRODUTO AS P
WHERE P.VALOR BETWEEN 20.0 AND 70.0;
--5)
SELECT COUNT(v.ID) QTD_VENDAS
FROM DBO.VENDA v;
--6)
SELECT COUNT(F.TIPO) QTD_VETERINARIO
FROM DBO.FUNCIONARIO F
WHERE F.TIPO = 'V';
--7)
SELECT COUNT(F.TIPO) QTD_ATENDENTE
FROM DBO.FUNCIONARIO F
WHERE F.TIPO = 'A';
--8)
SELECT P.NOME, P.VALOR
FROM DBO.PRODUTO P
WHERE P.VALOR < 30.0;
--9)
SELECT DISTINCT (p.PORTE) DIFERENTES_PORTES
FROM DBO.PET p;
--10)
SELECT F.TIPO, AVG(F.SALARIO) SALÁRIO
FROM DBO.FUNCIONARIO AS F
GROUP BY F.TIPO;


