USE PROJETO;

SELECT * FROM DBO.FUNCIONARIO;
SELECT * FROM DBO.FORMA_PAGAMENTO;
SELECT * FROM DBO.CLIENTE;
SELECT * FROM DBO.PET;
SELECT * FROM DBO.CLIENTE_PET;
SELECT * FROM DBO.PRODUTO;
SELECT * FROM DBO.VENDA;
SELECT * FROM DBO.PRODUTO_VENDA;
SELECT * FROM DBO.PRONTUARIO;

